package com.bazgab.h2db_rest_api.demo.model;


import jakarta.persistence.*;
import lombok.*;

@Entity
@Table(name = "Books")
@Getter
@Setter
@ToString
@AllArgsConstructor
@NoArgsConstructor
public class Book {
    //We have to annotate with @Id and @GeneratedValue so JPA understands these values don't have to
    //be created manually in the db, but instead autogenerated by JPA
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    private String title;
    private String author;

}
